### ISSUE TITLE
Error while trying to run the codes on the data dataset -- using: train.py 

### ISSUE THREAD

**Issue by aylin-msvn** [CRIPAC-DIG/tgm-dlm#8]
Here is the detail of my error: 

wandb: Find logs at: wandb/run-20241213_003300-uo3ydkh2/logs
Traceback (most recent call last):
  File "/mnt/c/TGM_DLM/improved-diffusion/scripts/train.py", line 207, in <module>
    mp.spawn(main_worker,args=(world_size,),nprocs=world_size,join=True)
  File "/home/aylin/miniconda3/envs/torch/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aylin/miniconda3/envs/torch/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/aylin/miniconda3/envs/torch/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 189, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/aylin/miniconda3/envs/torch/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/mnt/c/TGM_DLM/improved-diffusion/scripts/train.py", line 122, in main_worker
    ).run_loop()
      ^^^^^^^^^^
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/train_util.py", line 195, in run_loop
    self.run_step(batch, cond)
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/train_util.py", line 217, in run_step
    self.forward_backward(batch, cond)
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/train_util.py", line 277, in forward_backward
    losses = compute_losses()
             ^^^^^^^^^^^^^^^^
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/respace.py", line 100, in training_losses
    return super().training_losses(self._wrap_model(model), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/gaussian_diffusion.py", line 240, in training_losses
    return self.training_losses_e2e(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/gaussian_diffusion.py", line 1429, in training_losses_e2e
    model_output = model(x_t, self._scale_timesteps(t),desc_state,desc_mask)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/TGM_DLM/improved-diffusion/improved_diffusion/respace.py", line 132, in __call__
    return self.model(x, new_ts,*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...

    attention_scores = attention_scores + attention_mask
                       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (256) must match the size of tensor b (64) at non-singleton dimension 2

**Comment by Deno-V** [comment]
Have you run pip install -e transformers/. ?

**Comment by Deno-V** [comment]
Problem solved : )
